spring:
  application:
    name: hotel
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel_ms
    username: postgres
    password: 1976
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8090

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka

info:
  app:
    name: hotel
    description: hotel booking
    version: 1.0.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        register-health-indicator: true

springdoc:
  api-docs:
    path: /api-doc
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true