spring:
  application:
    name: mailserver
  kafka:
    bootstrap-servers: localhost:9092
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka

server:
  port: 9000


springdoc:
  api-docs:
    path: /api-doc
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: mailserver

logging:
  pattern:
    correlation: "[${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
